name: "Podcast RSS Feed generator with github actions"
author: "Navindu Sachintha"
description: "Generates RSS feed for podcast from a YAML file"

runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "aperture"
  color: "red"
inputs:
  email:
    description: The commiters email address
    required: true
    default: ${{ github.actor }}@localhost
  name:
    description: The committer's name
    required: true
    default: ${{ github.actor }}
